name: 🐛 Bug report
description: Report a reproducible bug or regression.
labels: ["status: needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! **The issue tracker is ONLY used for reporting bugs.** New feature suggestions and questions should be submitted through our user feedback form in the product.
  - type: checkboxes
    id: terms
    attributes:
      label: Can we access your project?
      # label: Has your issue been reported?
      # description: Please search to see if an issue already exists for the bug you encountered.
      options:
      #   - label: I have searched the existing issues and confirm it has not been reported.
      #     required: true
        - label: I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true  
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Please be detailed as possible here so we can help diagnose the issue.
        Issues cannot be accepted if they are too vague. For example, "project fails to build" would not be reproducible.
      placeholder: |
        1. Create new page
        2. Add container widget
        3. Set width = 123
        4. Click Run
        5. Observe that project doesn't build
    validations:
      required: true
  - type: checkboxes
    id: reproducible-from-blank
    attributes:
      label: Reproducible from Blank
      description: It's super helpful if the steps to reproduce start from a blank project. 
      options:
        - label: The steps to reproduce above start from a blank project.
          required: false
  - type: input
    id: bugcode
    attributes:
      label: Bug Report Code (Required)
      description: |
        Generate by right clicking inside Widget Tree and selecting "Get Bug Report Code". 
        This helps the team assess your issue. Create a code by going to the widget tree, right clicking on the affected widget, and selecting “Get Bug Report Code”. 
        If the bug is not specific to a widget, selecting any widget will work.
      placeholder: ex. ITFXhfH104V2sdRE+aXIYflViiowGUwbUOc7j9VEGAsjCePkP4k1Pc7CUFZpSOqHTGxUPk6Ikk8fw+zOv+zhEewpAw+CGapawbphH1yjEA8=
    validations:
      required: true
  - type: textarea
    attributes:
      label: Visual documentation
      description: |
        Images and/or a brief video showing the the steps to reproduce the issue you are reporting.
       
        Adding images and video snippets will help to speed up investigation and allow us to resolve issues more quickly.
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Include relevant details about the environment you experienced the bug in.
        Examples:
          - **FlutterFlow version**: v3.1 (released Feb 27, 2023)
          - **Platform** (e.g. Web, MacOS Desktop): Web
          - **Browser name and version** (web): Chrome 107.0.5304.110
          - **Operating system and version** (desktop): macOS Monterey 12.2.1
      value: |
          - FlutterFlow version: 
          - Platform:
          - Browser name and version:
          - Operating system and version affected: 
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: How has this issue affected you? What are you trying to accomplish? This helps us assess the priority!
    validations:
      required: false
  # - type: textarea
  #   attributes:
  #     label: Additional Info
  #     description: |
  #       Any extra screenshots, recordings, links, references, or anything else that will give us more context about the issue you are encountering.

  #       Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  #   validations:
  #     required: false

