blank_issues_enabled: false
contact_links:
  - name: FlutterFlow Community
    url: https://community.flutterflow.io/
    about: Please ask and answer questions, share suggestions, and discuss app ideas here.
