name: Automatic issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign Triage'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: hariprasadms,bulgariamitko,Hariprasadms,kevintonb,SameerShahzad99
                  numOfAssignee: 1
                  allowSelfAssign: false
            - name: 'Auto-assign Eng'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: agreaves,Agreaves,aemelyanovff,wenkaifan0720,victoriahuang1,katherineqian,avishal-cyber,sbis04
                  numOfAssignee: 1
                  allowSelfAssign: false
